spring:
  application:
    name: microservice-gateway-zuul

server:
  port: 8050

eureka:
  client:
    service-url: 
      defaultZone: http://user:password@localhost:8761/eureka
      
  instance:
    prefer-ip-address: true

zuul:
  ignored-services: '*'
  routes:
    microservice-provider-user: /user/**